package org.beatonma.commons.snommoc

/**
 * snommorg.org API JSON key values. Use constants to avoid errors caused by typos.
 */
internal object Contract {
    const val PARLIAMENTDOTUK = "parliamentdotuk"

    const val API_KEY = "key"

    // Generic
    const val NAME = "name"
    const val TITLE = "title"
    const val DESCRIPTION = "description"
    const val URL = "url"
    const val CATEGORY = "category"
    const val ORGANISATION = "organisation"
    const val CONTENT_TYPE = "content_type"
    const val LINKS = "links"

    /**
     * Most IDs used are the same as those used on Parliament API sources
     * and are referenced via PARLIAMENTDOTUK.
     *
     * Only use ID when the referenced ID was generated by us.
     */
    const val ID = "id"

    // Time
    const val DATE = "date"
    const val START = "start"
    const val END = "end"

    /* Political entities */
    const val PARTY = "party"
    const val CONSTITUENCY = "constituency"
    const val HOUSE = "house"
    const val MP = "mp"
    const val ELECTION = "election"
    const val ELECTION_TYPE = "election_type"

    // Constituency
    const val BOUNDARY = "boundary"
    const val RESULTS = "results"
    const val ELECTORATE = "electorate"
    const val TURNOUT = "turnout"
    const val TURNOUT_FRACTION = "turnout_fraction"
    const val RESULT = "result"
    const val MAJORITY = "majority"
    const val CANDIDATES = "candidates"
    const val PARTY_NAME = "party_name"
    const val ORDER = "order"
    const val KML = "kml"
    const val AREA = "area"
    const val BOUNDARY_LENGTH = "boundary_length"
    const val CENTER_LATITUDE = "center_latitude"
    const val CENTER_LONGITUDE = "center_longitude"

    const val CONSTITUENCY_ID = "constituency_id"
    const val ELECTION_ID = "election_id"


    // Divisions
    const val DIVISION = "division"
    const val VOTE_TYPE = "vote_type"
    const val VOTES = "votes"
    const val VOTE = "vote"
    const val PASSED = "passed"
    const val AYES = "ayes"
    const val NOES = "noes"
    const val ABSTENTIONS = "abstentions"
    const val DID_NOT_VOTE = "did_not_vote"
    const val NON_ELIGIBLE = "non_eligible"
    const val SUSPENDED_OR_EXPELLED = "suspended_or_expelled"
    const val ERRORS = "errors"
    const val DEFERRED_VOTE = "deferred_vote"
    const val WHIPPED_VOTE = "whipped_vote"

    // Member profile
    const val ACTIVE = "active"
    const val IS_MP = "is_mp"
    const val IS_LORD = "is_lord"
    const val AGE = "age"
    const val DATE_OF_BIRTH = "date_of_birth"
    const val DATE_OF_DEATH = "date_of_death"
    const val GENDER = "gender"
    const val PLACE_OF_BIRTH = "place_of_birth"
    const val PORTRAIT = "portrait"
    const val CURRENT_POST = "current_post"
    const val TOWN = "town"
    const val COUNTRY = "country"
    const val SUBJECT = "subject"

    // Member posts
    const val GOVERNMENTAL = "governmental"
    const val PARLIAMENTARY = "parliamentary"
    const val OPPOSITION = "opposition"

    // Member committees
    const val CHAIR = "chair"

    // Member career stuff
    const val PROFILE = "profile"
    const val ADDRESS = "address"
    const val POSTS = "posts"
    const val COMMITTEES = "committees"
    const val HOUSES = "houses"
    const val INTERESTS = "interests"
    const val EXPERIENCES = "experiences"
    const val SUBJECTS = "subjects"
    const val CONSTITUENCIES = "constituencies"
    const val PARTIES = "parties"

    // Member experience

    // Member financial interest
    const val CREATED = "created"
    const val AMENDED = "amended"
    const val DELETED = "deleted"
    const val REGISTERED_LATE = "registered_late"

    // Addresses
    const val POSTCODE = "postcode"
    const val PHONE = "phone"
    const val FAX = "fax"
    const val EMAIL = "email"
    const val PHYSICAL = "physical"
    const val WEB = "web"

    // Bills
    const val LAST_UPDATE = "last_update"
    const val IS_ACT = "is_act"
    const val IS_DEFEATED = "is_defeated"
    const val WITHDRAWN_AT = "withdrawn_at"
    const val SESSION_INTRODUCED = "session_introduced"
    const val SESSIONS = "sessions"
    const val PUBLICATIONS = "publications"
    const val SESSION = "session"
    const val TYPE = "type"
    const val SPONSOR = "sponsor"
    const val SPONSORS = "sponsors"
    const val CURRENT_STAGE = "current_stage"
    const val STAGES = "stages"
    const val SITTINGS = "sittings"
    const val SITTING_LATEST = "sitting_latest"

    /* Social */
    const val SNOMMOC_TOKEN = "token"
    const val GOOGLE_TOKEN = "gtoken"
    const val USERNAME = "username"
    const val COMMENTS = "comments"
    const val TEXT = "text"
    const val CREATED_ON = "created_on"
    const val MODIFIED_ON = "modified_on"
    const val TARGET_TYPE = "target_type"

    // Account management
    const val ACCOUNT_NEW_USERNAME = "new_username"
    const val ACCOUNT_ACTION_CHANGE_USERNAME = "rename"
    const val ACCOUNT_ACTION = "action"

    // Zeitgeist
    const val MOTD = "motd"
    const val ZEITGEIST_PEOPLE = "people"
    const val ZEITGEIST_DIVISIONS = "divisions"
    const val ZEITGEIST_BILLS = "bills"
    const val ZEITGEIST_TARGET = "target"
    const val ZEITGEIST_REASON = "reason"
    const val ZEITGEIST_PRIORITY = "priority"
}
